Repository 390MiniCapstone/Polaris, pull requests merged in 2025-02, with the labels that each got.

#62 Added unit tests to the homescreen component
  Polaris-FE/app/__tests__/homescreen.test.tsx
  Polaris-FE/components/BottomSheetComponent.tsx
  Polaris-FE/components/__tests__/BottomSheetComponent.test.tsx
  Polaris-FE/jest-setup.ts
Labels: chore

#66 created hooks and services for google auth and calendar
  Polaris-FE/app.config.js
  Polaris-FE/app/__tests__/homescreen.test.tsx
  Polaris-FE/constants/GoogleCalendar.ts
  Polaris-FE/constants/GoogleEvent.ts
  Polaris-FE/firebase/firebaseConfig.ts
  Polaris-FE/hooks/useGoogleAuth.ts
  Polaris-FE/hooks/useGoogleCalendar.ts
  Polaris-FE/hooks/useGoogleNextEvent.ts
  Polaris-FE/package-lock.json
  Polaris-FE/package.json
  Polaris-FE/services/__tests__/googleCalendarService.test.ts
  Polaris-FE/services/googleCalendarService.ts
  Polaris-FE/tsconfig.json
Labels: chore

#70 63 task update GitHub issue templates and add documentation templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/task.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: documentation

#84 #83: fixed casing for husky script
  .husky/pre-commit
Labels: bug

#104 Bug Fix CodeCov not Showing on `main` Branch
  .github/workflows/polaris.yml
  Polaris-FE/.gitignore
  Polaris-FE/package-lock.json
  Polaris-FE/package.json
Labels: bug

#105 Update issue templates
  .github/ISSUE_TEMPLATE/acceptance-test.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/task.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: acceptance test

#86 Feature/highlight current buildings
  Polaris-FE/components/Map.tsx
  Polaris-FE/hooks/__tests__/useCurrentBuilding.test.tsx
  Polaris-FE/hooks/useCurrentBuilding.ts
  Polaris-FE/hooks/useMapLocation.ts
  Polaris-FE/package-lock.json
  Polaris-FE/package.json
Labels: user story

#102 Feature/searching
  .DS_Store
  Polaris-FE/app.config.js
  Polaris-FE/app/index.tsx
  Polaris-FE/components/BottomSheetComponent.tsx
  Polaris-FE/components/GooglePlacesInput.tsx
  Polaris-FE/components/__tests__/BottomSheetComponent.test.tsx
  Polaris-FE/components/__tests__/GooglePlacesInput.test.tsx
  Polaris-FE/package-lock.json
  Polaris-FE/package.json
  Polaris-FE/utils/mapHandlers.ts
Labels: user story

#107 Implemented navigation feature
  Polaris-FE/app/__tests__/homescreen.test.tsx
  Polaris-FE/app/index.tsx
  Polaris-FE/components/BottomSheetComponent.tsx
  Polaris-FE/components/Map.tsx
  Polaris-FE/components/MapButtons.tsx
  Polaris-FE/components/Navigation/Instructions.tsx
  Polaris-FE/components/Navigation/Navigation.tsx
  Polaris-FE/components/Navigation/NavigationInfo.tsx
  Polaris-FE/components/Navigation/NavigationPolyline.tsx
  Polaris-FE/components/Navigation/TravelModeToggle.tsx
  Polaris-FE/components/Navigation/__tests__/Instructions.text.tsx
  Polaris-FE/components/Navigation/__tests__/Navigation.test.tsx
  Polaris-FE/components/Navigation/__tests__/NavigationInfo.test.tsx
  Polaris-FE/components/Navigation/__tests__/NavigationPolyline.test.tsx
  Polaris-FE/components/Navigation/__tests__/TransportMode.test.tsx
  Polaris-FE/components/Navigation/__tests__/__snapshots__/Instructions.text.tsx.snap
  Polaris-FE/components/Navigation/__tests__/__snapshots__/TransportMode.test.tsx.snap
  Polaris-FE/components/__tests__/BottomSheetComponent.test.tsx
  Polaris-FE/components/__tests__/Map.test.tsx
  Polaris-FE/components/__tests__/MapButtons.test.tsx
  Polaris-FE/components/__tests__/NavigationButtons.test.tsx
  Polaris-FE/constants/mapConstants.ts
  Polaris-FE/constants/types.ts
  Polaris-FE/hooks/useMapLocation.ts
  Polaris-FE/package-lock.json
  Polaris-FE/package.json
  Polaris-FE/services/__tests__/googleMapsRoutes.test.ts
  Polaris-FE/services/googleMapsRoutes.ts
  Polaris-FE/utils/__tests__/mapHandlers.test.ts
  Polaris-FE/utils/__tests__/navigationUtils.test.ts
  Polaris-FE/utils/mapHandlers.ts
  Polaris-FE/utils/navigationUtils.ts
  Polaris-FE/utils/refs.ts
Labels: user story

#108 Removed location dependency to fix fetching & updated input styling
  Polaris-FE/components/GooglePlacesInput.tsx
Labels: fix
