Repository 390MiniCapstone/Polaris, pull requests merged in 2025-03, with the labels that each got.

#122 [TASK] Setup ms clarity on native builds
  Polaris-FE/.gitignore
  Polaris-FE/app.config.js
  Polaris-FE/app/index.tsx
  Polaris-FE/hooks/useClarity.ts
  Polaris-FE/package-lock.json
  Polaris-FE/package.json
Labels: task

#113 card to display next class
  Polaris-FE/app.config.js
  Polaris-FE/app/__tests__/homescreen.test.tsx
  Polaris-FE/app/_layout.tsx
  Polaris-FE/app/oauthredirect.tsx
  Polaris-FE/components/BottomSheetComponent.tsx
  Polaris-FE/components/Navigation/__tests__/NextClassCard.test.tsx
  Polaris-FE/components/NextClassComponent/NextClassCard.styles.ts
  Polaris-FE/components/NextClassComponent/NextClassCard.tsx
  Polaris-FE/components/__tests__/BottomSheetComponent.test.tsx
  Polaris-FE/constants/GoogleEvent.ts
  Polaris-FE/contexts/AuthContext/AuthContext.tsx
  Polaris-FE/contexts/AuthContext/authService.ts
  Polaris-FE/contexts/AuthContext/authStorage.ts
  Polaris-FE/contexts/ContextProvider/GlobalContextProvider.tsx
  Polaris-FE/hooks/useGoogleCalendar.ts
  Polaris-FE/hooks/useNextClassTimer.ts
  Polaris-FE/hooks/useSelectedCalendar.ts
  Polaris-FE/jest-setup.ts
  Polaris-FE/package-lock.json
  Polaris-FE/package.json
Labels: user story

#127 [TASK] Setup E2E Testing with Maestro
  .DS_Store
  .gitignore
  Polaris-FE/.gitignore
  Polaris-FE/components/BottomSheetComponent.tsx
  Polaris-FE/components/MapButtons.tsx
  Polaris-FE/components/NextClassComponent/NextClassCard.tsx
  Polaris-FE/maestro/114-google-calendar-card.yml
  Polaris-FE/maestro/93-enable-easy-campus-switching.yml
  Polaris-FE/maestro/94-display-building-information.yml
  Polaris-FE/maestro/97-display-current-location.yml
  Polaris-FE/package.json
  docs/frontend/dev-installation.md
  docs/frontend/end-to-end-testing.md
  docs/index.md
Labels: task, acceptance test

#138 [TASK] Added SVG Tool and Appropriate Documentation
  Polaris-FE/package.json
  Polaris-FE/tools/SVGCoordinateTool.html
  docs/frontend/end-to-end-testing.md
  docs/frontend/tools.md
  docs/index.md
Labels: task

#140 [DOC] Created PR templates for bugs, docs, tasks, and user stories
  .github/PULL_REQUEST_TEMPLATE/bug.md
  .github/PULL_REQUEST_TEMPLATE/documentation.md
  .github/PULL_REQUEST_TEMPLATE/task.md
  .github/PULL_REQUEST_TEMPLATE/user-story.md
Labels: documentation

#133 Fix SonarQube Low Errors
  Polaris-FE/__mocks__/expo-router.jsx
  Polaris-FE/app/oauthredirect.tsx
  Polaris-FE/components/BottomSheetComponent/OutdoorBottomSheetComponent.tsx
  Polaris-FE/components/Map.tsx
  Polaris-FE/components/MapButtons.tsx
  Polaris-FE/components/Navigation/Navigation.tsx
  Polaris-FE/components/Navigation/NavigationInfo.tsx
  Polaris-FE/components/NextClassComponent/NextClassCard.tsx
  Polaris-FE/contexts/AuthContext/AuthContext.tsx
  Polaris-FE/eslint.config.js
  Polaris-FE/hooks/useGoogleAuth.ts
  Polaris-FE/utils/mapHandlers.ts
Labels: task

#118 Created a navigation context
  Polaris-FE/app/__tests__/homescreen.test.tsx
  Polaris-FE/app/_layout.tsx
  Polaris-FE/app/index.tsx
  Polaris-FE/components/BottomSheetComponent/OutdoorBottomSheetComponent.tsx
  Polaris-FE/components/GooglePlacesInput.tsx
  Polaris-FE/components/Map.tsx
  Polaris-FE/components/MapButtons.tsx
  Polaris-FE/components/Navigation/Instructions.tsx
  Polaris-FE/components/Navigation/Navigation.tsx
  Polaris-FE/components/Navigation/NavigationInfo.tsx
  Polaris-FE/components/Navigation/NavigationPolyline.tsx
  Polaris-FE/components/Navigation/TravelModeToggle.tsx
  Polaris-FE/components/Navigation/__tests__/Instructions.test.tsx
  Polaris-FE/components/Navigation/__tests__/Instructions.text.tsx
  Polaris-FE/components/Navigation/__tests__/Navigation.test.tsx
  Polaris-FE/components/Navigation/__tests__/NavigationInfo.test.tsx
  Polaris-FE/components/Navigation/__tests__/NavigationPolyline.test.tsx
  Polaris-FE/components/Navigation/__tests__/TransportMode.test.tsx
  Polaris-FE/components/Navigation/__tests__/TravelModeToggle.test.tsx
  Polaris-FE/components/Navigation/__tests__/__snapshots__/Instructions.text.tsx.snap
  Polaris-FE/components/Navigation/__tests__/__snapshots__/TransportMode.test.tsx.snap
  Polaris-FE/components/__tests__/GooglePlacesInput.test.tsx
  Polaris-FE/components/__tests__/Map.test.tsx
  Polaris-FE/components/__tests__/MapButtons.test.tsx
  Polaris-FE/components/__tests__/OutdoorBottomSheetComponent.test.tsx
  Polaris-FE/contexts/ContextProvider/GlobalContextProvider.tsx
  Polaris-FE/contexts/NavigationContext/NavigationContext.tsx
  Polaris-FE/contexts/NavigationContext/__tests__/NavigationContext.test.tsx
  Polaris-FE/hooks/__tests__/useGoogleMapsRoute.test.ts
  Polaris-FE/hooks/useGoogleMapsRoute.ts
  Polaris-FE/services/__tests__/googleMapsRoutes.test.ts
  Polaris-FE/utils/mapHandlers.ts
  Polaris-FE/utils/navigationUtils.ts
  Polaris-FE/utils/refs.ts
Labels: task

#141 Created a theme context and custom theme functionality
  Polaris-FE/app/_layout.tsx
  Polaris-FE/app/index.tsx
  Polaris-FE/components/Buildings/Buildings.tsx
  Polaris-FE/components/ColorblindButton.tsx
  Polaris-FE/components/Map.tsx
  Polaris-FE/components/Navigation/NavigationPolyline.tsx
  Polaris-FE/components/Navigation/__tests__/NavigationPolyline.test.tsx
  Polaris-FE/components/Styles/ColorblindButton.ts
  Polaris-FE/components/__tests__/ColorblindButton.test.tsx
  Polaris-FE/components/__tests__/Map.test.tsx
  Polaris-FE/constants/themeOptions.ts
  Polaris-FE/contexts/ContextProvider/GlobalContextProvider.tsx
  Polaris-FE/contexts/ThemeProvider/ThemeContext.ts
  Polaris-FE/contexts/ThemeProvider/ThemeContextProvider.tsx
  Polaris-FE/contexts/ThemeProvider/__tests__/ThemeProvider.test.tsx
  Polaris-FE/hooks/useTheme.ts
  Polaris-FE/utils/themeOptions.ts
Labels: user story

#143 Fixed the reliability issue reported by SonarQube.
  Polaris-FE/__mocks__/expo-router.jsx
Labels: task

#145 Made Current Building colors update with the theme
  Polaris-FE/components/Map.tsx
  Polaris-FE/components/__tests__/Map.test.tsx
  Polaris-FE/utils/themeOptions.ts
Labels: bug, fix

#147 Added error handling and loading state for fetching routes
  Polaris-FE/app/__tests__/homescreen.test.tsx
  Polaris-FE/app/index.tsx
  Polaris-FE/components/Navigation/Navigation.tsx
  Polaris-FE/components/Navigation/NavigationInfo.tsx
  Polaris-FE/components/Navigation/NavigationPolyline.tsx
  Polaris-FE/components/Navigation/__tests__/Navigation.test.tsx
  Polaris-FE/components/Navigation/__tests__/NavigationInfo.test.tsx
  Polaris-FE/components/Navigation/__tests__/NavigationPolyline.test.tsx
  Polaris-FE/contexts/NavigationContext/NavigationContext.tsx
  Polaris-FE/contexts/NavigationContext/__tests__/NavigationContext.test.tsx
  Polaris-FE/hooks/__tests__/useGoogleMapsRoute.test.ts
  Polaris-FE/hooks/useGoogleMapsRoute.ts
  Polaris-FE/package-lock.json
  Polaris-FE/package.json
  Polaris-FE/services/__tests__/googleMapsRoutes.test.ts
  Polaris-FE/services/googleMapsRoutes.ts
  Polaris-FE/utils/__tests__/navigationUtils.test.ts
  Polaris-FE/utils/navigationUtils.ts
Labels: bug, fix

#150 fixed google signin with comma from decomp
  Polaris-FE/contexts/AuthContext/AuthContext.tsx
Labels: bug
