Repository 390MiniCapstone/Polaris, pull requests merged in 2025-01, with the labels that each got.

#2 PL0: Created react native expo app
  Polaris-FE/.gitignore
  Polaris-FE/README.md
  Polaris-FE/app.json
  Polaris-FE/app/(tabs)/_layout.tsx
  Polaris-FE/app/(tabs)/explore.tsx
  Polaris-FE/app/(tabs)/index.tsx
  Polaris-FE/app/+not-found.tsx
  Polaris-FE/app/_layout.tsx
  Polaris-FE/assets/fonts/SpaceMono-Regular.ttf
  Polaris-FE/assets/images/adaptive-icon.png
  Polaris-FE/assets/images/favicon.png
  Polaris-FE/assets/images/icon.png
  Polaris-FE/assets/images/partial-react-logo.png
  Polaris-FE/assets/images/react-logo.png
  Polaris-FE/assets/images/react-logo@2x.png
  Polaris-FE/assets/images/react-logo@3x.png
  Polaris-FE/assets/images/splash-icon.png
  Polaris-FE/components/Collapsible.tsx
  Polaris-FE/components/ExternalLink.tsx
  Polaris-FE/components/HapticTab.tsx
  Polaris-FE/components/HelloWave.tsx
  Polaris-FE/components/ParallaxScrollView.tsx
  Polaris-FE/components/ThemedText.tsx
  Polaris-FE/components/ThemedView.tsx
  Polaris-FE/components/__tests__/ThemedText-test.tsx
  Polaris-FE/components/__tests__/__snapshots__/ThemedText-test.tsx.snap
  Polaris-FE/components/ui/IconSymbol.ios.tsx
  Polaris-FE/components/ui/IconSymbol.tsx
  Polaris-FE/components/ui/TabBarBackground.ios.tsx
  Polaris-FE/components/ui/TabBarBackground.tsx
  Polaris-FE/constants/Colors.ts
  Polaris-FE/hooks/useColorScheme.ts
  Polaris-FE/hooks/useColorScheme.web.ts
  Polaris-FE/hooks/useThemeColor.ts
  Polaris-FE/package-lock.json
  Polaris-FE/package.json
  Polaris-FE/scripts/reset-project.js
  Polaris-FE/tsconfig.json
Labels: chore

#3 Completed CI/CD Pipeline with Github Actions
  .github/workflows/polaris.yml
  Polaris-FE/package.json
Labels: chore

#7 Added husky pre-commit
  .husky/pre-commit
  Polaris-FE/components/Collapsible.tsx
  Polaris-FE/package-lock.json
  Polaris-FE/package.json
Labels: chore

#25 Addressed Husky defect
  .husky/pre-commit
  Polaris-FE/package-lock.json
  Polaris-FE/package.json
Labels: bug

#61 Added Map View with current location button, campus toggle, bottom sheet, and unit tests
  Polaris-FE/app.json
  Polaris-FE/app/(tabs)/index.tsx
  Polaris-FE/app/__tests__/homeScreen.test.tsx
  Polaris-FE/app/__tests__/layout.test.tsx
  Polaris-FE/app/_layout.tsx
  Polaris-FE/app/index.tsx
  Polaris-FE/assets/images/icon.png
  Polaris-FE/assets/images/splash-icon.png
  Polaris-FE/components/BottomSheetComponent.tsx
  Polaris-FE/components/Map.tsx
  Polaris-FE/components/NavigationButtons.tsx
  Polaris-FE/components/__tests__/BottomSheetComponent.test.tsx
  Polaris-FE/components/__tests__/Map.test.tsx
  Polaris-FE/components/__tests__/NavigationButtons.test.tsx
  Polaris-FE/constants/mapConstants.ts
  Polaris-FE/hooks/useMapLocation.ts
  Polaris-FE/package-lock.json
  Polaris-FE/package.json
  Polaris-FE/utils/mapHandlers.ts
Labels: user story, task
